sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt update && sudo apt install -y jp2a imagemagick
install:
  - sudo pip install -r requirements.txt
  - sudo python setup.py install
script:
  - sudo jp2a --width=76 Images/Daisy_raw.jpg
  - sudo python ImageEncryptor 1 1 -e Images/Daisy_raw.jpg -o justin.png
  - sudo convert justin.png jpg:- | jp2a --width=76 -
  - sudo python ImageEncryptor 1 1 -d justin.png -o justin_out.png
  - sudo convert justin_out.png jpg:- | jp2a --width=76 -