sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt update && sudo apt install -y jp2a imagemagick
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - jp2a --width=76 Images/Daisy_raw.jpg
  - python ImageEncryptor 1 1 -e Images/Daisy_raw.jpg -o justin.png
  - convert justin.png jpg:- | jp2a --width=76 -
  - python ImageEncryptor 1 1 -d justin.png -o justin_out.png
  - convert justin_out.png jpg:- | jp2a --width=76 -